AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create a Windows instance for the DE-Extract scenario.

Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: The key pair to use for the Windows instance.
  VPC:
    Type: AWS::EC2::VPC::Id
    Description: The VPC Id to deploy the Windows instance into.
  Subnet:
    Type: AWS::EC2::Subnet::Id
    Description: The subnet Id to deploy the Windows instance into.
  SecurityGroupIds:
    Type: List<AWS::EC2::SecurityGroup::Id>
    Description: The security group Ids to associate with the Windows instance.
  LatestWindowsAmiId:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-windows-latest/Windows_Server-2019-English-Full-Base
    Description: The latest Windows AMI Id.

Resources:
  WindowsInstanceRolePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: 
        Fn::Sub: "Windows-client-${AWS::StackName}"
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - 's3:Get*'
              - 's3:List*'
            Resource: '*'
      Roles:
        - Ref: WindowsInstanceRole
    DeletionPolicy: Delete

  WindowsInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - Ref: WindowsInstanceRole

  WindowsInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref LatestWindowsAmiId
      InstanceType: t2.micro
      KeyName: !Ref KeyName
      SubnetId: !Ref Subnet
      SecurityGroupIds: !Ref SecurityGroupIds
      IamInstanceProfile: !Ref WindowsInstanceProfile
      Tags:
        - Key: Name
          Value: DE-Extract-Windows-Instance
